[project]
name = "punch-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.0.0",
    "faiss-cpu>=1.13.2",
    "fastapi==0.115.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.15",
    "langchain-groq>=1.1.2",
    "langchain-huggingface>=1.2.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "sentence-transformers>=5.2.3",
    "uvicorn>=0.41.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv]
torch-backend = "cpu"
dependency-metadata = [
    { name = "torch", requires-dist = ["filelock", "fsspec", "jinja2", "networkx", "setuptools", "sympy", "typing-extensions"] },
]
